-- golden fixture dump (generated by tools/extract-golden-devin-cline.ts)
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;
CREATE TABLE "__drizzle_migrations" (
				id SERIAL PRIMARY KEY,
				hash text NOT NULL,
				created_at numeric
			);
CREATE TABLE `message_nodes` (
	`row_id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`session_id` text NOT NULL,
	`node_id` integer NOT NULL,
	`parent_node_id` integer,
	`chat_message` text NOT NULL,
	`created_at` integer NOT NULL,
	`metadata` text,
	FOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE TABLE `prompt_history` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`content` text NOT NULL,
	`timestamp` integer NOT NULL,
	`session_id` text NOT NULL,
	`is_shell` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE TABLE `sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`working_directory` text NOT NULL,
	`backend_type` text NOT NULL,
	`model` text NOT NULL,
	`agent_mode` text NOT NULL,
	`created_at` integer NOT NULL,
	`last_activity_at` integer NOT NULL,
	`title` text NOT NULL,
	`main_chain_id` integer NOT NULL,
	`shell_last_seen_index` integer DEFAULT 0 NOT NULL,
	`cogs_json` text DEFAULT '[]' NOT NULL,
	`workspace_dirs` text DEFAULT '[]' NOT NULL,
	`hidden` integer DEFAULT 0 NOT NULL,
	`metadata` text DEFAULT '{}' NOT NULL
);
INSERT INTO "__drizzle_migrations" ("id", "hash", "created_at") VALUES (NULL, '66c781b7f6d2bc3fe055eb8ca60852075bef2ff214bc281a52586a445879057e', 1788642531821);
INSERT INTO "message_nodes" ("row_id", "session_id", "node_id", "parent_node_id", "chat_message", "created_at", "metadata") VALUES (1, 'devin-basic-1', 0, NULL, '{"message_id":"d3f4571a-27b3-4b73-8a3b-f8e997717825","role":"user","content":"do the thing","metadata":{"num_tokens":null,"is_user_input":true,"request_id":null,"metrics":null,"finish_reason":null,"extensions":{},"created_at":"2023-11-14T22:13:20.000Z","telemetry":{"source":"user","operation":"input"}}}', 1700000000, NULL);
INSERT INTO "message_nodes" ("row_id", "session_id", "node_id", "parent_node_id", "chat_message", "created_at", "metadata") VALUES (2, 'devin-basic-1', 1, 0, '{"message_id":"0e4fe491-a715-4922-a15e-7cc108a60f74","role":"assistant","content":"done — the thing is done","tool_calls":[],"metadata":{"num_tokens":null,"is_user_input":null,"request_id":null,"metrics":null,"finish_reason":"stop","extensions":{},"generation_model":"swe-2-high","created_at":"2023-11-14T22:15:00.000Z","telemetry":{"source":"assistant","operation":"inference"}}}', 1700000100, NULL);
INSERT INTO "message_nodes" ("row_id", "session_id", "node_id", "parent_node_id", "chat_message", "created_at", "metadata") VALUES (3, 'devin-basic-2', 0, NULL, '{"message_id":"6d241b90-f132-4db6-a468-40a373bc4b6d","role":"user","content":"plan only, do not touch files","metadata":{"num_tokens":null,"is_user_input":true,"request_id":null,"metrics":null,"finish_reason":null,"extensions":{},"created_at":"2023-11-14T22:30:00.000Z","telemetry":{"source":"user","operation":"input"}}}', 1700001000, NULL);
INSERT INTO "prompt_history" ("id", "content", "timestamp", "session_id", "is_shell") VALUES (1, 'do the thing', 1700000000000, 'devin-basic-1', 0);
INSERT INTO "prompt_history" ("id", "content", "timestamp", "session_id", "is_shell") VALUES (2, '!git status', 1700000050000, 'devin-basic-1', 1);
INSERT INTO "prompt_history" ("id", "content", "timestamp", "session_id", "is_shell") VALUES (3, 'plan only, do not touch files', 1700001000000, 'devin-basic-2', 0);
INSERT INTO "sessions" ("id", "working_directory", "backend_type", "model", "agent_mode", "created_at", "last_activity_at", "title", "main_chain_id", "shell_last_seen_index", "cogs_json", "workspace_dirs", "hidden", "metadata") VALUES ('devin-basic-1', '/work/demo', 'windsurf', 'swe-2-high', 'accept-edits', 1700000000, 1700000300, 'Basic Devin session', 1, 0, '[{"source":{"Session":"User"},"lifetime":{"Unique":"core/plan_mask"},"set_system_prefix":null,"append_system_messages":[],"context":[],"footer_messages":[],"user_display":[],"permissions":[],"tool_availability":null,"model":null},{"source":{"Session":"User"},"lifetime":{"Unique":"core/accept_edits"},"set_system_prefix":null,"append_system_messages":[],"context":[],"footer_messages":[],"user_display":[],"permissions":[],"tool_availability":null,"model":null},{"source":{"Session":"System"},"lifetime":{"Unique":"core/parallel-tool-calls"},"set_system_prefix":null,"append_system_messages":[],"context":[],"footer_messages":[],"user_display":[],"permissions":[],"tool_availability":null,"model":null},{"source":{"Session":"System"},"lifetime":{"Unique":"core/model"},"set_system_prefix":null,"append_system_messages":[],"context":[],"footer_messages":[],"user_display":[],"permissions":[],"tool_availability":null,"model":null}]', '[]', 0, '{"total_credit_cost":0,"total_acu_cost":0,"response_dimensions":[{"uid":"agent_messages","group_title":"Response Statistics","kind":{"CumulativeMetric":{"label":"Agent messages","value":0,"tail":" message","plural_tail":" messages","prefix":""}}},{"uid":"model","group_title":"Response Statistics","kind":{"Metric":{"label":"Model","value":"Imported from Cline"}}}]}');
INSERT INTO "sessions" ("id", "working_directory", "backend_type", "model", "agent_mode", "created_at", "last_activity_at", "title", "main_chain_id", "shell_last_seen_index", "cogs_json", "workspace_dirs", "hidden", "metadata") VALUES ('devin-basic-2', '/work/other', 'windsurf', 'swe-1-7-medium', 'plan', 1700001000, 1700002000, 'Hidden second session', 0, 0, '[]', '["/work/other","/work/shared"]', 1, 'null');
INSERT INTO "sqlite_sequence" ("name", "seq") VALUES ('message_nodes', 3);
INSERT INTO "sqlite_sequence" ("name", "seq") VALUES ('prompt_history', 3);
COMMIT;
