// GENERATED by tools/build-binary.ts — do not edit by hand.
// The build script regenerates this file with one `type: "file"` import per
// apps/server/ui-dist/ asset (staged from apps/web/dist/client). The empty map
// below is the checked-in fallback so `tsc` and plain `bun` runs work without
// a web build — UI serving simply stays off.
export const embeddedUiFiles: Readonly<Record<string, string>> = {};
