-- golden fixture dump (generated by tools/extract-golden-devin-cline.ts)
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;
CREATE TABLE "__drizzle_migrations" (
				id SERIAL PRIMARY KEY,
				hash text NOT NULL,
				created_at numeric
			);
CREATE TABLE `message_nodes` (
	`row_id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`session_id` text NOT NULL,
	`node_id` integer NOT NULL,
	`parent_node_id` integer,
	`chat_message` text NOT NULL,
	`created_at` integer NOT NULL,
	`metadata` text,
	FOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE TABLE `prompt_history` (
	`id` integer PRIMARY KEY AUTOINCREMENT NOT NULL,
	`content` text NOT NULL,
	`timestamp` integer NOT NULL,
	`session_id` text NOT NULL,
	`is_shell` integer DEFAULT 0 NOT NULL,
	FOREIGN KEY (`session_id`) REFERENCES `sessions`(`id`) ON UPDATE no action ON DELETE no action
);
CREATE TABLE rendered_commits (
      id INTEGER PRIMARY KEY AUTOINCREMENT, session_id TEXT NOT NULL,
      sequence_number INTEGER NOT NULL, rendered_html TEXT NOT NULL,
      created_at INTEGER NOT NULL);
CREATE TABLE `sessions` (
	`id` text PRIMARY KEY NOT NULL,
	`working_directory` text NOT NULL,
	`backend_type` text NOT NULL,
	`model` text NOT NULL,
	`agent_mode` text NOT NULL,
	`created_at` integer NOT NULL,
	`last_activity_at` integer NOT NULL,
	`title` text NOT NULL,
	`main_chain_id` integer NOT NULL,
	`shell_last_seen_index` integer DEFAULT 0 NOT NULL,
	`cogs_json` text DEFAULT '[]' NOT NULL,
	`workspace_dirs` text DEFAULT '[]' NOT NULL,
	`hidden` integer DEFAULT 0 NOT NULL,
	`metadata` text DEFAULT '{}' NOT NULL
);
CREATE TABLE subagent_heads (
      session_id TEXT NOT NULL, agent_id TEXT NOT NULL,
      chain_node_id INTEGER NOT NULL, updated_at INTEGER NOT NULL,
      PRIMARY KEY (session_id, agent_id));
CREATE TABLE tool_call_state (
      session_id TEXT NOT NULL, tool_call_id TEXT NOT NULL,
      tool_call_json TEXT, tool_call_update_json TEXT,
      PRIMARY KEY (session_id, tool_call_id));
INSERT INTO "__drizzle_migrations" ("id", "hash", "created_at") VALUES (NULL, '66c781b7f6d2bc3fe055eb8ca60852075bef2ff214bc281a52586a445879057e', 1788642531821);
INSERT INTO "message_nodes" ("row_id", "session_id", "node_id", "parent_node_id", "chat_message", "created_at", "metadata") VALUES (1, 'devin-raw-1', 0, NULL, '{"message_id":"msg-raw-0","role":"system","content":"You are Devin, an AI software engineer."}', 1700200000, NULL);
INSERT INTO "message_nodes" ("row_id", "session_id", "node_id", "parent_node_id", "chat_message", "created_at", "metadata") VALUES (2, 'devin-raw-1', 1, 0, '{"message_id":"msg-raw-1","role":"user","content":"fix the flaky test","metadata":{"num_tokens":null,"is_user_input":true,"request_id":null,"metrics":null,"finish_reason":null,"extensions":{},"created_at":"2023-11-17T05:46:40.000Z","telemetry":{"source":"user","operation":"input"}}}', 1700200000, NULL);
INSERT INTO "message_nodes" ("row_id", "session_id", "node_id", "parent_node_id", "chat_message", "created_at", "metadata") VALUES (3, 'devin-raw-1', 2, 1, '{"message_id":"msg-raw-2","role":"assistant","content":"","thinking":{"thinking":"The test flakes under parallel load — check the shared fixture.","signature":"sealed.v1.9f8e7d6c"},"tool_calls":[{"id":"toolu_01","name":"exec","arguments":{"command":"bun test --bail 1"},"index":0,"kind":"function"},{"id":"toolu_02","name":"read","arguments":{"file_path":"/work/repo/src/flaky.test.ts"},"index":1,"kind":"function"}],"metadata":{"num_tokens":42,"is_user_input":null,"request_id":"req-9f","metrics":{"ttft_ms":812,"input_tokens":9000,"output_tokens":42,"cache_read_tokens":12000,"cache_creation_tokens":800},"finish_reason":"tool_calls","extensions":{"chisel/tool_call_content":{"toolu_01":{"toolCallId":"toolu_01","title":"Ran command","status":"in_progress","locations":[],"kind":"execute","rawInput":{"command":"bun test --bail 1"}},"toolu_02":{"toolCallId":"toolu_02","title":"Read file","status":"completed","locations":[{"path":"/work/repo/src/flaky.test.ts","line":1}],"kind":"read","rawInput":{"file_path":"/work/repo/src/flaky.test.ts"}}}},"generation_model":"swe-1.5","created_at":"2023-11-17T05:47:30.000Z","telemetry":{"source":"assistant","operation":"inference"}}}', 1700200050, '{"summarized_from":null,"num_tokens_preceding":512,"is_system_prefix":null}');
INSERT INTO "message_nodes" ("row_id", "session_id", "node_id", "parent_node_id", "chat_message", "created_at", "metadata") VALUES (4, 'devin-raw-1', 3, 2, '{"message_id":"msg-raw-3","role":"tool","content":"1 failed, 9 passed","tool_call_id":"toolu_01","metadata":{"num_tokens":null,"is_user_input":null,"request_id":null,"metrics":null,"finish_reason":null,"extensions":{"chisel/tool_result_meta":{"success":false,"kind":"exec"},"chisel/terminal_output":{"exit":{"terminal_id":"t0","exit_code":1}},"chisel/tool_call_timing":{"duration_ms":4321}},"created_at":"2023-11-17T05:50:00.000Z","telemetry":{"source":"tool_result","operation":"exec"}}}', 1700200200, NULL);
INSERT INTO "message_nodes" ("row_id", "session_id", "node_id", "parent_node_id", "chat_message", "created_at", "metadata") VALUES (5, 'devin-raw-1', 4, 3, '{"message_id":"msg-raw-4","role":"tool","content":"test(''flaky'', async () => { /* … */ })","tool_call_id":"toolu_02","metadata":{"num_tokens":null,"is_user_input":null,"request_id":null,"metrics":null,"finish_reason":null,"extensions":{"chisel/tool_result_meta":{"success":true,"kind":"read"}},"created_at":"2023-11-17T05:50:50.000Z","telemetry":{"source":"tool_result","operation":"read"}}}', 1700200250, NULL);
INSERT INTO "message_nodes" ("row_id", "session_id", "node_id", "parent_node_id", "chat_message", "created_at", "metadata") VALUES (6, 'devin-raw-1', 5, 4, '{"message_id":"msg-raw-5","role":"assistant","content":"Found it — the shared DB fixture races. Serialized it; suite is green.","metadata":{"num_tokens":61,"is_user_input":null,"request_id":"req-a1","metrics":{"ttft_ms":220,"input_tokens":9100,"output_tokens":61,"cache_read_tokens":null,"cache_creation_tokens":null},"finish_reason":"stop","extensions":{},"generation_model":"swe-1.5","created_at":"2023-11-17T05:56:40.000Z","telemetry":{"source":"assistant","operation":"inference"}}}', 1700200600, NULL);
INSERT INTO "message_nodes" ("row_id", "session_id", "node_id", "parent_node_id", "chat_message", "created_at", "metadata") VALUES (7, 'devin-raw-1', 6, 5, '{"content":{"odd":true},"note":"no role, no message_id"}', 1700200700, 'not-json{');
INSERT INTO "prompt_history" ("id", "content", "timestamp", "session_id", "is_shell") VALUES (1, 'fix the flaky test', 1700200000000, 'devin-raw-1', 0);
INSERT INTO "prompt_history" ("id", "content", "timestamp", "session_id", "is_shell") VALUES (2, '!bun test --bail 1', 1700200010000, 'devin-raw-1', 1);
INSERT INTO "rendered_commits" ("id", "session_id", "sequence_number", "rendered_html", "created_at") VALUES (1, 'devin-raw-1', 0, '<p>hi</p>', 1700200000);
INSERT INTO "sessions" ("id", "working_directory", "backend_type", "model", "agent_mode", "created_at", "last_activity_at", "title", "main_chain_id", "shell_last_seen_index", "cogs_json", "workspace_dirs", "hidden", "metadata") VALUES ('devin-raw-1', '/work/repo', 'windsurf', 'swe-1.5', 'accept-edits', 1700200000, 1700200600, 'Raw chisel session', 5, 2, '[{"source":{"Session":"System"},"lifetime":{"Unique":"core/model"},"set_system_prefix":null,"append_system_messages":[],"context":[],"footer_messages":[],"user_display":[],"permissions":[],"tool_availability":null,"model":"swe-1.5"}]', '["/work/repo"]', 0, '{"total_credit_cost":12.5,"total_acu_cost":3}');
INSERT INTO "sessions" ("id", "working_directory", "backend_type", "model", "agent_mode", "created_at", "last_activity_at", "title", "main_chain_id", "shell_last_seen_index", "cogs_json", "workspace_dirs", "hidden", "metadata") VALUES ('devin-raw-2', '/work/repo', 'windsurf', 'swe-1.5-mini', 'accept-edits', 1700200300, 1700200300, 'Sub run (no nodes)', 0, 0, '[]', '[]', 0, '{}');
INSERT INTO "subagent_heads" ("session_id", "agent_id", "chain_node_id", "updated_at") VALUES ('devin-raw-1', 'devin-raw-2', 2, 1700200300);
INSERT INTO "tool_call_state" ("session_id", "tool_call_id", "tool_call_json", "tool_call_update_json") VALUES ('devin-raw-1', 'toolu_01', '{"toolCallId":"toolu_01","title":"Ran command","status":"in_progress","kind":"execute"}', '{"toolCallId":"toolu_01","status":"failed","_meta":{"cognition.ai/terminal_exit":{"exit_code":1}}}');
INSERT INTO "tool_call_state" ("session_id", "tool_call_id", "tool_call_json", "tool_call_update_json") VALUES ('devin-raw-1', 'toolu_02', '{"toolCallId":"toolu_02","title":"Read file","status":"completed","kind":"read"}', 'garbage{not json');
INSERT INTO "sqlite_sequence" ("name", "seq") VALUES ('message_nodes', 7);
INSERT INTO "sqlite_sequence" ("name", "seq") VALUES ('prompt_history', 2);
INSERT INTO "sqlite_sequence" ("name", "seq") VALUES ('rendered_commits', 1);
COMMIT;
