-- golden fixture dump (generated by tools/extract-golden-devin-cline.ts)
PRAGMA foreign_keys = OFF;
BEGIN TRANSACTION;
CREATE TABLE sessions (
  session_id TEXT PRIMARY KEY,
  source TEXT NOT NULL,
  pid INTEGER NOT NULL,
  started_at TEXT NOT NULL,
  ended_at TEXT,
  exit_code INTEGER,
  status TEXT NOT NULL,
  status_lock INTEGER NOT NULL DEFAULT 0,
  interactive INTEGER NOT NULL,
  provider TEXT NOT NULL,
  model TEXT NOT NULL,
  cwd TEXT NOT NULL,
  workspace_root TEXT NOT NULL,
  team_name TEXT,
  enable_tools INTEGER NOT NULL,
  enable_spawn INTEGER NOT NULL,
  enable_teams INTEGER NOT NULL,
  parent_session_id TEXT,
  parent_agent_id TEXT,
  agent_id TEXT,
  conversation_id TEXT,
  is_subagent INTEGER NOT NULL DEFAULT 0,
  prompt TEXT,
  metadata_json TEXT,
  transcript_path TEXT NOT NULL DEFAULT '',
  hook_path TEXT NOT NULL,
  messages_path TEXT,
  updated_at TEXT NOT NULL
);
INSERT INTO "sessions" ("session_id", "source", "pid", "started_at", "ended_at", "exit_code", "status", "status_lock", "interactive", "provider", "model", "cwd", "workspace_root", "team_name", "enable_tools", "enable_spawn", "enable_teams", "parent_session_id", "parent_agent_id", "agent_id", "conversation_id", "is_subagent", "prompt", "metadata_json", "transcript_path", "hook_path", "messages_path", "updated_at") VALUES ('1700001000_fghij', 'cli', 0, '2025-01-02T00:00:00.000Z', '2025-01-02T00:05:00.000Z', 0, 'completed', 0, 1, 'cline-pass', 'cline-pass/swe-2-high', '/work', '/work', NULL, 1, 1, 1, NULL, NULL, NULL, NULL, 0, 'what''s in this image?', '{"sessionHistoryOrigin":{"mode":"user","version":"3.0.61"},"source":"cli","provider":"cline-pass","model":"cline-pass/swe-2-high","enableTools":true,"enableSpawn":true,"enableTeams":true,"interactive":true,"mode":"act"}', '', '', '{{DATA_DIR}}/sessions/1700001000_fghij/1700001000_fghij.messages.json', '2025-01-02T00:05:00.000Z');
COMMIT;
