#!/usr/bin/env bun
/**
 * Builds the single-file `sepia` binary:
 *
 *   1. `vp run sepia-web#build` → apps/web/dist/client (SPA shell + assets)
 *   2. copy the bundle to apps/server/ui-dist/ (keeps the embed inside the
 *      server app's boundary; the repo's no-cross-app-import lint forbids
 *      apps/server importing from apps/web)
 *   3. regenerate apps/server/src/ui.assets.gen.ts — one
 *      `import ... with { type: "file" }` per asset, so `bun build --compile`
 *      embeds the whole bundle into the binary ($bunfs virtual files at runtime)
 *   4. `bun build apps/sepia/src/main.ts --compile` → ./sepia
 *
 * Usage: bun tools/build-binary.ts [--skip-web-build] [--outfile <path>]
 */
import { cp, mkdir, readdir, stat, writeFile } from "node:fs/promises";
import { join, relative, resolve } from "node:path";

const repoRoot = resolve(import.meta.dir, "..");
const distDir = join(repoRoot, "apps/web/dist/client");
const stagingDir = join(repoRoot, "apps/server/ui-dist");
const manifestPath = join(repoRoot, "apps/server/src/ui.assets.gen.ts");
const entrypoint = join(repoRoot, "apps/sepia/src/main.ts");

const args = process.argv.slice(2);
const skipWebBuild = args.includes("--skip-web-build");
const outfileIndex = args.indexOf("--outfile");
const outfile =
  outfileIndex !== -1 ? resolve(args[outfileIndex + 1] ?? "sepia") : join(repoRoot, "sepia");

const run = (argv: string[]): void => {
  const proc = Bun.spawnSync(argv, { cwd: repoRoot, stdio: ["inherit", "inherit", "inherit"] });
  if (proc.exitCode !== 0) {
    console.error(`build-binary: command failed (${proc.exitCode}): ${argv.join(" ")}`);
    process.exit(proc.exitCode ?? 1);
  }
};

const walk = async (dir: string): Promise<string[]> => {
  const entries = await readdir(dir, { withFileTypes: true });
  const files: string[] = [];
  for (const entry of entries) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) files.push(...(await walk(full)));
    else if (entry.isFile()) files.push(full);
  }
  return files;
};

if (!skipWebBuild) {
  console.log("build-binary: building web bundle (vp run sepia-web#build)");
  run(["vp", "run", "sepia-web#build"]);
}

const files = (await walk(distDir)).sort();
if (files.length === 0) {
  console.error(`build-binary: ${distDir} is empty — run the web build first`);
  process.exit(1);
}
if (!files.some((file) => file === join(distDir, "index.html"))) {
  console.error("build-binary: dist/client has no index.html — is SPA mode enabled?");
  process.exit(1);
}

// Stage the bundle inside apps/server so the generated imports stay within
// the app boundary (lint: sepia/no-cross-app-import).
await cp(distDir, stagingDir, { recursive: true, force: true });

const specDir = resolve(manifestPath, "..");
const lines: string[] = [
  "// GENERATED by tools/build-binary.ts — do not edit by hand.",
  `// ${files.length} embedded files from apps/web/dist/client (staged at ui-dist/).`,
];
const entries: string[] = [];
files.forEach((file, index) => {
  const staged = join(stagingDir, relative(distDir, file));
  const specifier = relative(specDir, staged);
  lines.push(`import f${index} from "${specifier}" with { type: "file" };`);
  const urlPath = `/${relative(distDir, file).split("\\").join("/")}`;
  entries.push(`  ${JSON.stringify(urlPath)}: f${index},`);
});
lines.push(
  "",
  "export const embeddedUiFiles: Readonly<Record<string, string>> = {",
  ...entries,
  "};",
  "",
);
await mkdir(specDir, { recursive: true });
await writeFile(manifestPath, lines.join("\n"));
console.log(`build-binary: wrote ${manifestPath} (${files.length} files)`);

console.log(`build-binary: compiling ${entrypoint} -> ${outfile}`);
run(["bun", "build", entrypoint, "--compile", "--minify", "--outfile", outfile]);

const { size } = await stat(outfile);
console.log(`build-binary: done — ${outfile} (${(size / 1024 / 1024).toFixed(1)} MiB)`);
